<?php

namespace Database\Seeders;

use App\Models\Recipe;
use Illuminate\Database\Seeder;

class RecipeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // for ($i = 0; $i < 10; $i++) {
        //     Recipe::create([
        //         'name' => fake()->name,
        //         'description' => fake()->name,
        //         'is_active' => fake()->boolean,
        //     ]);
        // }
        $recipe = [
            ['name' => 'Injera', 'category_id' => 1, 'description' => 'Injera is a sour fermented pancake-like flatbread with a slightly spongy texture, traditionally made of teff flour. In Ethiopia, Eritrea, and some parts of Sudan, injera is the staple. Injera is central to the dining process, like bread or rice elsewhere.', 'is_active' => 0],
            ['name' => 'Pad Thai', 'category_id' => 16, 'description' => 'Pad thai, phat thai, or phad thai, is a stir-fried rice noodle dish commonly served as a street food in Thailand as part of the countrys cuisine. It is typically made with rice noodles, shrimp, peanuts, a scrambled egg, and bean sprouts, among other vegetables. The ingredients are fried in a wok.', 'is_active' => 1],
            ['name' => 'Chicken Biryani', 'category_id' => 11, 'description' => 'Biryani is a mixed rice dish originating among the Muslims of the Indian subcontinent as a variety of Persian pilaf. It is made with Indian spices, rice, and usually some type of meat or in some cases without any meat, and sometimes, in addition, eggs and potatoes.', 'is_active' => 0],
            ['name' => 'Tossed Salad', 'category_id' => 3, 'description' => 'A salad made by tossing greens in a dressing, often including other vegetables like tomato and cucumber.', 'is_active' => 0],
            ['name' => 'Cuban-Style Picadillo', 'category_id' => 6, 'description' => 'Picadillo (Spanish pronunciation: [pikaˈðijo], "mince") is a traditional dish in many Latin American countries and the Philippines. It is made with ground meat (most commonly beef), tomatoes (tomato sauce may be used as a substitute), and also raisins, olives, and other ingredients that vary by region.', 'is_active' => 0],
            ['name' => 'Greek Spinach', 'category_id' => 10, 'description' => 'Spanakopita is a Greek savory spinach pie. It often also contains cheese, typically feta, and may then be called spanakotiropita.', 'is_active' => 0],
            ['name' => 'Infused Creme Brulee', 'category_id' => 9, 'description' => 'This basic vanilla-bean recipe is so versatile and can be used as the base for many different variations of this classic dessert. The only problem is that it goes fast even when you triple and quadruple the batch! ', 'is_active' => 1],
            ['name' => 'Italian Pasta Salad', 'category_id' => 12, 'description' => 'Pasta salad (pasta fredda) is a salad dish prepared with one or more types of pasta, almost always chilled, and most often tossed in a vinegar, oil, or mayonnaise-based dressing. It is typically served as an appetizer, side dish or a main course. Pasta salad is often regarded as a spring or summertime meal, but it can be served any time of year.', 'is_active' => 0],
            ['name' => 'Tiramisu', 'category_id' => 12, 'description' => 'Tiramisu is a coffee-flavoured Italian dessert. It is made of ladyfingers (savoiardi) dipped in coffee, layered with a whipped mixture of eggs, sugar, and mascarpone cheese, flavoured with cocoa. The recipe has been adapted into many varieties of cakes and other desserts.', 'is_active' => 0],
            ['name' => 'Yummy Vegan Pesto Classico', 'category_id' => 12, 'description' => 'This is a classic recipe everyone use and love. Nutritional yeast is substituted for the traditionally used dairy. Tasty on pasta, bread, sandwiches, omelets, etc. Try adding sun-dried tomato slices post-completion for an added boost of rich flavor. P.S. - It also freezes beautifully.', 'is_active' => 1],
            ['name' => 'Bellini Cocktail', 'category_id' => 12, 'description' => 'A Bellini is a cocktail made with Prosecco and peach purée or nectar. It originated in Venice, Italy.', 'is_active' => 1],
            ['name' => 'Minestrone', 'category_id' => 12, 'description' => 'Minestrone is a thick soup of Italian origin made with vegetables, often with the addition of pasta or rice, sometimes both. Common ingredients include beans, onions, celery, carrots, leaf vegetables, stock, parmesan cheese and tomatoes.', 'is_active' => 1],
            ['name' => 'Lasagna', 'category_id' => 12, 'description' => 'Lasagna is a type of pasta, possibly one of the oldest types, made of very wide, flat sheets. Either term can also refer to an Italian dish made of stacked layers of lasagna alternating with fillings such as ragù, béchamel sauce, vegetables, cheeses, and seasonings and spices.', 'is_active' => 0],
            ['name' => 'Veal Marsala', 'category_id' => 12, 'description' => 'Veal marsala was created by 19th century food critic Roberto Giovanni who, after first tasting chicken marsala. thought it would taste much better with the meat of a more tender animal. Rather than give a negative review to the dish in the next days food write-up.', 'is_active' => 0],
            ['name' => 'Simple Meat Lasagna', 'category_id' => 12, 'description' => 'This lasagna with ground beef and whole wheat noodles is an easy, yet hearty family-pleasing dish.', 'is_active' => 0],
            ['name' => 'Italian Pasta e Fagioli', 'category_id' => 12, 'description' => 'Pasta e fagioli, meaning "pasta and beans", is a traditional Italian pasta soup. It is often called pasta fasul or pasta fazool in the New York Italian dialect, derived from its Neapolitan name, pasta e fasule.', 'is_active' => 1],
            ['name' => 'Carbonara with Pancetta', 'category_id' => 12, 'description' => 'One of the most Classic Italian Pasta dishes, La Carbonara, Pancetta and Egg Pasta. A creamy delicious dinner recipe without the cream. Ready in 15 minutes or less.', 'is_active' => 0],
            ['name' => 'Shepherds Pie', 'category_id' => 4, 'description' => 'Shepherds pie, cottage pie, or in its French version hachis Parmentier is a savoury dish of cooked minced meat topped with mashed potato and baked. The meat used may be either previously cooked or freshly minced. The usual meats are beef or lamb.', 'is_active' => 1],
            ['name' => 'Yorkshire Pudding', 'category_id' => 4, 'description' => 'Yorkshire pudding is a baked pudding made from a batter of eggs, flour, and milk or water. A common British side dish, it is a versatile food that can be served in numerous ways depending on its ingredients, size, and the accompanying components of the meal. As a first course, it can be served with onion gravy.', 'is_active' => 0],
            ['name' => 'Victoria Sponge Cake', 'category_id' => 4, 'description' => 'Sponge cake is a light cake made with egg whites, flour and sugar, sometimes leavened with baking powder. Some sponge cakes do not contain egg yolks, like angel food cake, but most of them do. Sponge cakes, leavened with beaten eggs, originated during the Renaissance, possibly in Spain.', 'is_active' => 0],
            ['name' => 'Bangers and Mash', 'category_id' => 4, 'description' => 'Bangers and mash, also known as sausages and mash, is a traditional British dish, consisting of sausages served with mashed potatoes. It may consist of one of a variety of flavoured sausages made of pork, lamb, or beef. The dish is usually served with onion gravy, but may also include fried onions and peas.', 'is_active' => 0],
            ['name' => 'Yule Log', 'category_id' => 4, 'description' => 'The Yule log, Yule clog, or Christmas block is a specially selected log burnt on a hearth as a winter tradition in regions of Europe, and subsequently North America. The origin of the folk custom is unclear.', 'is_active' => 0],
            ['name' => 'Irish Boiled Dinner', 'category_id' => 4, 'description' => 'Easy boiled dinner of mouthwatering, tender corned beef with potatoes, cabbage, and carrots. This is my great-grandmothers recipe from Ireland. We served it with Irish soda bread and cornbread at our house. Use leftovers to make corned beef soup by reducing the broth and dicing up the leftover beef and vegetables.', 'is_active' => 0],
            ['name' => 'Schnitzel', 'category_id' => 8, 'description' => 'A schnitzel is a thin slice of meat. The meat is usually thinned by pounding with a meat tenderizer. Most commonly, the meat is breaded before frying. Breaded schnitzel is popular in many countries and is made using veal, pork, chicken, mutton, beef, or turkey.', 'is_active' => 1],
            ['name' => 'Currywurst', 'category_id' => 8, 'description' => 'Currywurst is a fast food dish of German origin consisting of steamed, fried sausage, usually pork, typically cut into bite-sized chunks and seasoned with curry ketchup, a sauce based on spiced ketchup or tomato paste topped with curry powder, or a ready-made ketchup seasoned with curry and other spices.', 'is_active' => 0],
            ['name' => 'German Currywurst', 'category_id' => 8, 'description' => 'The Currywurst has been a German institution since 1949. Learn how to make the BEST authentic curry ketchup and tradtional Currywurst!', 'is_active' => 1],
            ['name' => 'German New Year Pretzel', 'category_id' => 8, 'description' => 'A pretzel, from German pronunciation, standard German: Breze is a type of baked pastry made from dough that is commonly shaped into a knot. The traditional pretzel shape is a distinctive symmetrical form, with the ends of a long strip of dough intertwined and then twisted back onto itself in a particular way.', 'is_active' => 0],
            ['name' => 'Spanish Sangria', 'category_id' => 15, 'description' => 'Sangria is an alcoholic beverage originating in Spain and Portugal. Under EU regulations only those two Iberian nations can label their product as Sangria; similar products from different regions are differentiated in name.', 'is_active' => 0],
            ['name' => 'Marias Paella', 'category_id' => 15, 'description' => 'Paella is a rice dish originally from Valencia. While non-Spaniards commonly view it as Spains national dish, Spaniards almost unanimously consider it to be a dish from the Valencian region. Valencians, in turn, regard paella as one of their identifying symbols. It is one of the best-known dishes in Spanish cuisine.', 'is_active' => 0],
            ['name' => 'Pear Crisp', 'category_id' => 2, 'description' => 'Whether you save this idea for Thanksgiving dinner or prepare it for your next weeknight meal, a Pear Crisp is the perfect easy dessert recipe for fall! Sweet, warmly spiced pears are topped with a buttery, crunchy topping made with oats, brown sugar, and pecans for a simple, seasonal treat with just 15 minutes of prep. Add apples for an apple pear crisp, and serve a bowl warm with a scoop of vanilla ice cream and a drizzle of caramel sauce!', 'is_active' => 1],
            ['name' => 'Minnesota Wild Rice Salad', 'category_id' => 2, 'description' => 'Everyone thinks this is one of my best salads because it features wild rice—a major crop in my home state of Minnesota. Cashews give a subtle nutty flavor.', 'is_active' => 0],
            ['name' => 'Fish and Chips', 'category_id' => 2, 'description' => 'Fish and chips is a hot dish consisting of fried fish in batter, served with chips. The dish originated in England, where these two components had been introduced from separate immigrant cultures; it is not known who combined them.', 'is_active' => 0],
            ['name' => 'American-Style Potato Salad', 'category_id' => 2, 'description' => 'Potato salad is a salad dish made from boiled potatoes, usually containing a dressing and a variety of other ingredients such as boiled eggs and raw vegetables. In the United States, it is generally considered a side dish and usually accompanies the main course.', 'is_active' => 0],
            ['name' => 'Thanksgiving Dressing With Parsley, Sage and Thyme', 'category_id' => 2, 'description' => 'For those who havent completely given up on homemade stuffing and are looking for a simple, memorable stuffing, this sage stuffing recipe — and its tasty variations — will set you on the path in the right direction.', 'is_active' => 1],
            ['name' => 'American Blueberry Crisp', 'category_id' => 2, 'description' => 'Blueberry Crisp makes a quick and easy dessert that never disappoints! Learn how to make a blueberry crisp with an extra zing by adding a bit of lemon…so good! Much like Apple Crisp, this easy fruit crisp recipe is perfect served warm from the oven topped with a scoop of vanilla ice cream.', 'is_active' => 1],
            ['name' => 'Sloppy Joes', 'category_id' => 2, 'description' => 'A Sloppy Joe is a sandwich consisting of ground beef and onions in a tomato-based sauce served on a hamburger bun.', 'is_active' => 1],
            ['name' => 'Chicken and Rice Soup', 'category_id' => 2, 'description' => 'This easy Chicken Rice Soup recipe is a healthy soup that’s perfect for chilly days! It’s loaded with vegetables and brown rice, simmered in chicken broth and finished with a touch of creaminess.', 'is_active' => 0],
            ['name' => 'She Crab Soup', 'category_id' => 2, 'description' => 'She-crab soup is a rich soup, similar to bisque, made of milk or heavy cream, crab or fish stock, Atlantic blue crab meat, and crab roe, and a small amount of dry sherry added as it is plated.', 'is_active' => 1],
            ['name' => 'Cinnamon Rolls', 'category_id' => 2, 'description' => 'A cinnamon roll is a sweet roll commonly served in Northern Europe and North America. In Sweden it is called kanelbulle, in Denmark it is known as kanelsnegl, in Norway it is known as kanelbolle.', 'is_active' => 1],
            ['name' => 'Texas Caviar', 'category_id' => 2, 'description' => 'Texas caviar, also called cowboy caviar, is a Tex-Mex bean salad consisting of black-eyed peas lightly pickled in a vinaigrette-style dressing, often eaten as a dip accompaniment to tortilla chips.', 'is_active' => 1],
            ['name' => 'Clam Chowder', 'category_id' => 2, 'description' => 'Clam chowder is any of several chowder soups in American cuisine containing clams. In addition to clams, common ingredients include diced potatoes, salt pork, and onions. Other vegetables are not typically used. It is believed that clams were used in chowder because of the relative ease of harvesting them.', 'is_active' => 1],
            ['name' => 'Lukshen Noodle Kugel', 'category_id' => 2, 'description' => 'Kugel is a baked casserole, most commonly made from lokshen or Jewish egg noodles or potato. It is a traditional Ashkenazi Jewish dish, often served on Shabbat and Jewish holidays. American Jews also serve it for Thanksgiving dinner.', 'is_active' => 0],
            ['name' => 'Chef Johns Potato Pancakes', 'category_id' => 2, 'description' => 'The one and only way to not get perfectly crispy potato pancakes is to not squeeze them properly. More than half the procedure was dedicated to grating, soaking, draining, and squeezing the potatoes. If you dont thoroughly squeeze all the liquid from the potatoes, the pancakes just wont crisp up as well. Top with thinly sliced smoked salmon, sour cream, and fresh dill.', 'is_active' => 0],
            ['name' => 'Jewish Chicken Soup', 'category_id' => 2, 'description' => 'This traditional Jewish chicken soup is good for anything that ails you. Its the absolute best when youve got the flu, and its great on the second and third day. This recipe was passed down from my great-grandmother who needed to make the matzoh balls as heavy as possible to feed a hungry family. You can cut the matzoh meal by 1/2 cup to lighten the load.', 'is_active' => 1],
            ['name' => 'Pickled Eggs', 'category_id' => 5, 'description' => 'Pickled eggs are typically hard boiled eggs that are cured in vinegar or brine. As with many foods, this was originally a way to preserve the food so that it could be eaten months later.', 'is_active' => 0],
            ['name' => 'Turkey and Rice Soup', 'category_id' => 5, 'description' => 'Warming and light, Turkey and Rice Soup is a wonderful way to enjoy leftover turkey. Tender turkey, vegetables and rice are swirled in a savory broth and finished with a splash of fresh lemon juice and a bright blend of parsley, lemon zest, and garlic. A welcome and restorative meal after days of decadent eating.', 'is_active' => 1],
            ['name' => 'Macaroni Salad', 'category_id' => 5, 'description' => 'This is a classic, tasty, and oh-so easy macaroni salad recipe! Made with classic ingredient staples including celery, red pepper, and onion and dressed up in a simple creamy mayo-based dressing, this is guaranteed to be a hit at every cookout and potluck this year!', 'is_active' => 0],
            ['name' => 'Canadian Caesar', 'category_id' => 5, 'description' => 'A Caesar is a cocktail created and consumed primarily in Canada. It typically contains vodka, tomato juice and clam broth, hot sauce, and Worcestershire sauce, and is served with ice in a large, celery salt-rimmed glass, typically garnished with a stalk of celery and wedge of lime.', 'is_active' => 1],
            ['name' => 'Yassa Chicken', 'category_id' => 1, 'description' => 'Chicken Yassa is scrumptious West African comfort food that the whole world needs to know about. Delicious tender chicken and lots of caramelized onions in a sweet, spicy, lemony sauce.', 'is_active' => 0],
            ['name' => 'Lo Mein Noodles', 'category_id' => 7, 'description' => 'Slippery Lo Mein Noodles tossed in a Lo Mein Sauce with tons of veggies and protein of your choice. Takeout gold standard comes down to the right sauce and the right noodles – then you’re just 6 minutes away from noodle heaven!', 'is_active' => 0],
            ['name' => 'Bean Sprout Stir Fry', 'category_id' => 7, 'description' => 'Tauge goreng is an Indonesian savoury vegetarian dish made of stir-fried tauge with slices of tofu, ketupat or lontong rice cake and yellow noodles, served in a spicy oncom-based sauce. Tauge goreng is a specialty of Jakarta and Bogor city, West Java, Indonesia. ', 'is_active' => 0],
            ['name' => 'Green Mango and Papaya Salad in Thai Dressing (Yam Mamuang)', 'category_id' => 16, 'description' => 'Sweet and tart with umami lingering in the background, Thai green mango salad, or yum ma muang, relies heavily on the freshest ingredients.', 'is_active' => 1],
            ['name' => 'Hummus with Spiced n Baked Pita Chips', 'category_id' => 13, 'description' => 'This delicious dip is our go-to quick and easy snack for the dreaded unexpected "drop-by". A few pulses in the food processor and youve got a creamy, garlicky, lemony blend of chickpeas, roasted red peppers, olive oil and spices. Paired with addictive baked pita chips – wedges seasoned with cumin and salt – it’s no wonder they come a-knockin’ at all hours.', 'is_active' => 0],
            ['name' => 'Mojito', 'category_id' => 6, 'description' => 'Mojito is a traditional Cuban punch. The cocktail often consists of five ingredients: white rum, sugar, lime juice, soda water, and mint. Its combination of sweetness, citrus, and herbaceous mint flavors is intended to complement the rum, and has made the mojito a popular summer drink.', 'is_active' => 1],
            ['name' => 'Cuban Sandwich', 'category_id' => 6, 'description' => 'A Cuban sandwich is a variation of a ham and cheese sandwich that likely originated in cafes catering to Cuban workers in Tampa or Key West, two early Cuban immigrant communities in Florida centered on the cigar industry. Later on, Cuban exiles and expatriates brought it to Miami, where it is also very popular.', 'is_active' => 1],
            ['name' => 'Pisco Sour', 'category_id' => 14, 'description' => 'A pisco sour is an alcoholic cocktail of Peruvian origin that is typical of Peruvian cuisine. The drinks name comes from pisco, which is its base liquor, and the cocktail term sour, about sour citrus juice and sweetener components.', 'is_active' => 0],
            ['name' => 'Apfelstrudel (Apple Strudel)', 'category_id' => 8, 'description' => 'Apple strudel is a traditional Viennese strudel, a popular pastry in Austria, Bavaria, the Czech Republic, Northern Italy, Slovenia, and other countries in Europe that once belonged to the Austro-Hungarian Empire.', 'is_active' => 1],
            ['name' => 'Pork Schnitzel', 'category_id' => 8, 'description' => 'German pork schnitzel is an easy recipe and it’s perfect for busy weeknights. The pork chops are pounded into thin, tender cutlets which are breaded and sautéed, resulting in a crispy crust and juicy center.', 'is_active' => 0],
            ['name' => 'Cinnamon Apple Strudel', 'category_id' => 8, 'description' => 'Busy times call for easy desserts that have a sweet simplicity, like these flaky apple-cinnamon pastries. For our streamlined strudel, we folded convenient store-bought puff pastry around a four-ingredient filling of sauteed fruit.', 'is_active' => 1],
            ['name' => 'Apple Strudel', 'category_id' => 8, 'description' => 'Apple strudel is a traditional Viennese strudel, a popular pastry in Austria, Bavaria, the Czech Republic, Northern Italy, Slovenia, and other countries in Europe that once belonged to the Austro-Hungarian Empire.', 'is_active' => 0],
            ['name' => 'Chicken Schnitzel', 'category_id' => 8, 'description' => 'Chicken schnitzel is one of life’s great pleasures. This traditional Austrian recipe is popular in both Germany and Israel, as well as throughout the world. A well made schnitzel is fried golden and crisp on the outside, tender and moist within. Of course this simple, budget-friendly dish is easy to prepare, if you know a few key tips. In this post I share everything you need to know for cooking amazing schnitzel. In due time, this easy chicken schnitzel recipe is sure to become a mainstay in your kitchen. After all, it’s so simple and tasty!', 'is_active' => 0],
            ['name' => 'Greek Salad', 'category_id' => 10, 'description' => 'Greek salad or horiatiki salad is a popular salad in Greek cuisine generally made with pieces of tomatoes, cucumbers, onion, feta cheese, and olives and dressed with salt, Greek oregano, and olive oil. Common additions include green bell pepper slices or caper berries. ', 'is_active' => 0],
            ['name' => 'Greek Baklava', 'category_id' => 10, 'description' => 'Baklava is a delicious Greek dessert made up of layers of crispy phyllo dough, honey and nuts thats sooo easy to make. A Greek friend showed me how to make this fabulous recipe. ', 'is_active' => 1],
            ['name' => 'Omelet', 'category_id' => 9, 'description' => 'In cuisine, an omelette is a dish made from beaten eggs, fried with butter or oil in a frying pan. It is quite common for the omelette to be folded around fillings such as chives, vegetables, mushrooms, meat, cheese, onions or some combination of the above.', 'is_active' => 0],
            ['name' => 'Tuna Nicoise Salad', 'category_id' => 9, 'description' => 'This colourful tuna Niçoise salad makes the most of storecupboard ingredients - vary it for a special occasion by using fresh tuna.', 'is_active' => 1],
            ['name' => 'Bechamel: White Sauce', 'category_id' => 9, 'description' => 'Bechamel sauce is a sauce traditionally made from a white roux and milk. Bechamel may also be referred to as besciamella, besamel, or white sauce. French, Italian and Greek bechamel sauce recipes include salt and nutmeg as a seasoning base. Bechamel sauce is one of the "mother sauces" of French cuisine.', 'is_active' => 1],
            ['name' => 'Duck a lOrange', 'category_id' => 9, 'description' => 'Because a single duck rarely has enough meat to feed more than two or three people, Jacques Pépin prepares two ducks side by side when serving this classic dish to guests. And because hes roasting whole ducks, he cooks them until theyre well done, which results in the crispiest skin and best flavor.', 'is_active' => 0],
            ['name' => 'Onion Soup', 'category_id' => 9, 'description' => 'French onion soup is a soup usually based on meat stock and onions, and often served gratinéed with croutons or a larger piece of bread covered with cheese floating on top. Ancient in origin, the dish underwent a resurgence of popularity in the 1960s in the United States due to a greater interest in French cuisine.', 'is_active' => 1],
            ['name' => 'French Mussels', 'category_id' => 9, 'description' => 'Infused with rich flavours of a perfect, buttery broth with a hint of garlic, wine and parsley, French steamed mussels are ready in less than 20 minutes. Easy to make, mussels can be served as a meal with pasta and a simple side salad, OR as an appetizer with fresh or crusty bread. A modern twist on a classic recipe!', 'is_active' => 1],
            ['name' => 'Chicken in Red Wine', 'category_id' => 9, 'description' => 'Easy to make, Coq au Vin is a French dish with chicken and veggies braised in a flavorful wine sauce. Don’t be fooled by the name, this dish is actually easy and while it takes some time, a lot of it is hands-off while the dish bakes in the oven! It is perfect for those stay-at-home dinners or even special occasions!', 'is_active' => 0],
            ['name' => 'Chef Ricks French Bread', 'category_id' => 9, 'description' => 'A baguette is a long, thin type of bread of French origin that is commonly made from basic lean dough. It is distinguishable by its length and crisp crust. A baguette has a diameter of about 5 to 6 centimetres and a usual length of about 65 cm, although a baguette can be up to 1 m long.', 'is_active' => 0],
            ['name' => 'Beurre Blanc: White Butter Sauce', 'category_id' => 9, 'description' => 'Beurre blanc is a warm emulsified butter sauce made with a reduction of vinegar and/or white wine (normally Muscadet) and shallots into which softened whole butter is whisked in off the heat to prevent separation. The small amount of emulsifiers naturally found in butter are used to form an oil-in-water emulsion. Although similar to hollandaise in concept, it is considered neither a classic leading nor compound sauce. This sauce originates in Loire Valley cuisine.', 'is_active' => 1],
            ['name' => 'Genoise', 'category_id' => 9, 'description' => 'A génoise, also known as Genoese cake or Genovese cake, is an Italian sponge cake named after the city of Genoa and associated with Italian and French cuisine. Instead of using chemical leavening, air is suspended in the batter during mixing to provide volume.', 'is_active' => 0],
            ['name' => 'Lemon Chicken with Sauteed Spinach', 'category_id' => 12, 'description' => 'This simple, ultra-quick chicken dinner—packed with spinach and peppers—is delicious on its own or served over brown rice or your favorite pasta.', 'is_active' => 1],
            ['name' => 'Italian Lasagna', 'category_id' => 12, 'description' => 'Lasagna is a type of pasta, possibly one of the oldest types, made of very wide, flat sheets. Either term can also refer to an Italian dish made of stacked layers of lasagna alternating with fillings such as ragù, béchamel sauce, vegetables, cheeses, and seasonings and spices.', 'is_active' => 1],
            ['name' => 'Margherita Pizza - New York Style', 'category_id' => 12, 'description' => 'Pizza margherita, as the Italians call it, is a simple pizza hailing from Naples. When done right, margherita pizza features a bubbly crust, crushed San Marzano tomato sauce, fresh mozzarella and basil, a drizzle of olive oil, and a sprinkle of salt. That is all.', 'is_active' => 1],
            ['name' => 'Negroni', 'category_id' => 12, 'description' => 'A Negroni is an Italian cocktail, made of one part gin, one part vermouth rosso and one part Campari, garnished with orange peel. It is considered an apéritif. A traditionally made Negroni is stirred, not shaken; it is built over ice in an old-fashioned or rocks glass and garnished with a slice of orange.', 'is_active' => 1],
            ['name' => 'Italian Bolognese Sauce', 'category_id' => 12, 'description' => 'Bolognese sauce is a meat-based sauce in Italian cuisine, typical of the city of Bologna. It is customarily used to dress tagliatelle al ragù and to prepare lasagne alla bolognese.', 'is_active' => 0],
            ['name' => 'Minestrone', 'category_id' => 12, 'description' => 'Minestrone is a thick soup of Italian origin made with vegetables, often with the addition of pasta or rice, sometimes both. Common ingredients include beans, onions, celery, carrots, leaf vegetables, stock, parmesan cheese and tomatoes.', 'is_active' => 0],
            ['name' => 'Bolognese', 'category_id' => 12, 'description' => 'Bolognese sauce is a meat-based sauce in Italian cuisine, typical of the city of Bologna. It is customarily used to dress tagliatelle al ragù and to prepare lasagne alla bolognese.', 'is_active' => 1],
            ['name' => 'Lasagne', 'category_id' => 12, 'description' => 'Lasagna is a type of pasta, possibly one of the oldest types, made of very wide, flat sheets. Either term can also refer to an Italian dish made of stacked layers of lasagna alternating with fillings such as ragù, béchamel sauce, vegetables, cheeses, and seasonings and spices.', 'is_active' => 1],
            ['name' => 'Spaghetti Carbonara', 'category_id' => 12, 'description' => 'Carbonara is an Italian pasta dish from Rome made with eggs, hard cheese, cured pork and black pepper. The dish arrived at its modern form, with its current name, in the middle of the 20th century. The cheese is usually Pecorino Romano, Parmigiano-Reggiano, or a combination of the two.', 'is_active' => 0],
            ['name' => 'Tiramisu with Chocolate', 'category_id' => 12, 'description' => 'Creamy, chocolatey, and a snap to make, this chocolate lovers tiramisu gets an extra pick me up with a shot of coffee liquor.', 'is_active' => 0],
            ['name' => 'Italian Pasta Salad', 'category_id' => 12, 'description' => 'Fresh and easy pasta salad packed with crisp vegetables, fresh mozzarella, and tossed with a simple homemade dressing. The perfect side dish!', 'is_active' => 0],
            ['name' => 'Italian Turkey Meatballs', 'category_id' => 12, 'description' => 'Leaner than beef, these Turkey Meatballs are healthy, packed with flavor, and incredibly moist on the inside. A combination of fresh and dried herbs give these meatballs an Italian flare while also providing a balance of flavors.', 'is_active' => 1],
            // ['name' => 'Cherry Pie', 'category_id' => 2, 'description' => 'Cherry pie is a pie baked with a cherry filling. Traditionally, cherry pie is made with sour cherries rather than sweet cherries. Morello cherries are one of the most common kinds of cherry used, but other varieties such as the black cherry may also be used.', 'is_active' => 1],
            // ['name' => 'Mayonnaise', 'category_id' => 2, 'description' => 'Mayonnaise, colloquially referred to as "mayo", is a thick, cold, and creamy sauce or dressing commonly used on sandwiches, hamburgers, composed salads, and French fries. It also forms the base for various other sauces, such as tartar sauce, fry sauce, remoulade, salsa golf, and rouille.', 'is_active' => 0],
            // ['name' => 'Bbq Sauce', 'category_id' => 2, 'description' => 'Barbecue sauce is a sauce used as a marinade, basting, condiment, or topping for meat cooked in the barbecue cooking style, including pork or beef ribs and chicken. It is a ubiquitous condiment in the Southern United States and is used on many other foods as well.', 'is_active' => 1],
            // ['name' => 'American Grilled Cheese', 'category_id' => 2, 'description' => 'A grilled cheese sandwich is made by placing a cheese filling, often cheddar or American cheese, between two slices of bread, which is then heated until the bread browns and the cheese melts. A layer of butter or mayonnaise may be added to the outside of the bread for additional flavor and texture.', 'is_active' => 0],
            // ['name' => 'Club Sandwich', 'category_id' => 2, 'description' => 'A club sandwich, also called a clubhouse sandwich, is a sandwich consisting of bread, sliced cooked poultry, fried bacon, lettuce, tomato, and mayonnaise. It is often cut into quarters or halves and held together by cocktail sticks.', 'is_active' => 0],
            // ['name' => 'American Burgers', 'category_id' => 2, 'description' => 'A hamburger, or simply burger, is a food consisting of fillings—usually a patty of ground meat, typically beef—placed inside a sliced bun or bread roll.', 'is_active' => 0],
            // ['name' => 'Pound Cake', 'category_id' => 2, 'description' => 'Pound cake is a type of cake traditionally made with a pound of each of four ingredients: flour, butter, eggs, and sugar. Pound cakes are generally baked in either a loaf pan or a Bundt mold. They are sometimes served either dusted with powdered sugar, lightly glazed, or with a coat of icing.', 'is_active' => 0],
            // ['name' => 'Pretzels', 'category_id' => 2, 'description' => 'How to make easy homemade soft pretzels in less than 45 minutes. Dont forget the easy spicy cheese sauce!', 'is_active' => 0],
            // ['name' => 'Cheesecake', 'category_id' => 2, 'description' => 'Cheesecake is a sweet dessert consisting of one or more layers. The main, and thickest, layer consists of a mixture of a soft, fresh cheese, eggs, and sugar. If there is a bottom layer, it most often consists of a crust or base made from crushed cookies, graham crackers, pastry, or sometimes sponge cake.', 'is_active' => 0],
            // ['name' => 'American Potato Salad', 'category_id' => 2, 'description' => 'Just a good old fashioned, down home potato salad recipe that brings back memories of picnics in the park and family gatherings. Wonderful as it is or make it your own by adding additional ingredients of your choice.', 'is_active' => 1],
            // ['name' => 'Coleslaw with Caraway', 'category_id' => 2, 'description' => 'This mouth-watering recipe is ready in just 15 minutes and the ingredients detailed below can serve up to 6 people.', 'is_active' => 1],
            // ['name' => 'Fudge Brownies', 'category_id' => 2, 'description' => 'These homemade brownies are so much better than the box, and I bet you have what you need to make them already sitting in your kitchen.', 'is_active' => 0],
            // ['name' => 'Egg Cream', 'category_id' => 2, 'description' => 'An egg cream is a cold beverage consisting of milk, carbonated water, and flavored syrup, as a substitute for an ice cream float. Despite the name, the drink contains neither eggs nor cream.', 'is_active' => 1],
            // ['name' => 'Chicken and Coconut Soup', 'category_id' => 16, 'description' => 'This tom kha gai soup recipe (or Thai coconut chicken soup) is absolutely perfect. Rich and creamy yet tangy and salty, this Thai coconut chicken soup recipe is filling but light and positively bursting with flavor. ', 'is_active' => 1],
            // ['name' => 'Tomato Sauce', 'category_id' => 12, 'description' => 'Tomato sauce can refer to many different sauces made primarily from tomatoes, usually to be served as part of a dish, rather than as a condiment. Tomato sauces are common for meat and vegetables, but they are perhaps best known as bases for sauces for Mexican salsas and Italian pasta dishes.', 'is_active' => 1],
            // ['name' => 'Ragu Bolognese', 'category_id' => 12, 'description' => 'In Italian cuisine, ragù is a meat-based sauce that is commonly served with pasta. An Italian gastronomic society, Accademia Italiana della Cucina, documented several ragù recipes. The recipes common characteristics are the presence of meat and the fact that all are sauces for pasta.', 'is_active' => 0],
            // ['name' => 'Pesto', 'category_id' => 12, 'description' => 'Pesto is a sauce that traditionally consists of crushed garlic, European pine nuts, coarse salt, basil leaves, and hard cheese such as Parmigiano-Reggiano or Pecorino Sardo, all blended with olive oil. It originated in Genoa, the capital city of Liguria, Italy.', 'is_active' => 1],
            // ['name' => 'Tiramisu', 'category_id' => 12, 'description' => 'Tiramisu is a coffee-flavoured Italian dessert. It is made of ladyfingers dipped in coffee, layered with a whipped mixture of eggs, sugar, and mascarpone cheese, flavoured with cocoa. The recipe has been adapted into many varieties of cakes and other desserts.', 'is_active' => 0],
            // ['name' => 'Fish and Chips', 'category_id' => 4, 'description' => 'Fish and chips is a hot dish consisting of fried fish in batter, served with chips. The dish originated in England, where these two components had been introduced from separate immigrant cultures; it is not known who combined them.', 'is_active' => 0],
            // ['name' => 'Sauerbraten', 'category_id' => 8, 'description' => 'Sauerbraten is a traditional German roast of heavily marinated meat. It is regarded as a national dish of Germany, and is frequently served in German-style restaurants internationally. It can be prepared from a variety of meats, most often from beef, but also from venison, lamb and mutton, pork and horse.', 'is_active' => 0],
            // ['name' => 'Gazpacho', 'category_id' => 15, 'description' => 'Gazpacho or Gaspacho, also called Andalusian gazpacho, is a cold soup and drink made of raw, blended vegetables. It originated in the southern regions of the Iberian peninsula and spread into other areas. Gazpacho is widely eaten in Spain and Portugal, particularly during hot summers, since it is refreshing and cool.', 'is_active' => 1],
            // ['name' => 'Grilled Pork Chops with Barbecue Sauce', 'category_id' => 2, 'description' => 'These bbq pork chops are ready in just 30-minutes, plus they are super tender, tasty, and juicy when slathered in the easiest homemade BBQ sauce. Finger-licking-good and amazingly juicy, prepare for these pork chops to become your go-to for all the cookouts. ', 'is_active' => 0],
            // ['name' => 'Roast Turkey With Herbed Stuffing and Old-Fashioned Gravy', 'category_id' => 2, 'description' => 'These instructions are for a 12-pound turkey, which serves eight people. But you can easily scale it up for a bigger bird. Estimate about one pound of meat per person (one and a half pounds if you want lots of leftovers) and refer to the chart in the Test-Kitchen Tips, below, for the scaled-up cooking times.', 'is_active' => 1],
            // ['name' => 'Meat Loaf with Roasted Vegetables', 'category_id' => 2, 'description' => 'Your oven will be working double duty not only baking the meat loaf but also roasting vegetables to create this hearty, delicious one-dish meal.', 'is_active' => 1],
            // ['name' => 'Chocolate Egg Cream', 'category_id' => 2, 'description' => 'An egg cream is a cold beverage consisting of milk, carbonated water, and flavored syrup, as a substitute for an ice cream float. Despite the name, the drink contains neither eggs nor cream', 'is_active' => 1],
            // ['name' => 'Manhattan Clam Chowder', 'category_id' => 2, 'description' => 'New England clam chowder is thick, creamy, and milky-white. Manhattan clam chowder is tomatoey, brothy, and clear. Both types share a clean, briny, and slightly-sweet flavor thanks to the clams—but thats about it.', 'is_active' => 0],

        ];

        foreach ($recipe as $item) {
            Recipe::create([
                'name' => $item['name'],
                'category_id' => $item['category_id'],
                'description' => $item['description'],
                'is_active' => $item['is_active'],
            ]);
        }
    }
}
